TrainingArguments:
  num_train_epochs: 1
  warmup_steps: 10
  per_device_train_batch_size: 1
  weight_decay: 0.01
  logging_steps: 5
  eval_strategy: "steps"
  eval_steps: 50
  save_steps: 1000000
  gradient_accumulation_steps: 2
  fp16: False
  report_to: none